# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170224_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
